apiVersion: v1
kind: Pod
metadata:
  name: ideation-pod
  labels:
    app: ideation
spec:
  containers:
    - name: ideation
      image: org.ideation/rest-layer:0.0.1-SNAPSHOT
      env:
        - name: PROFILE
          value: develop


---
apiVersion: v1
kind: Service
metadata:
  name: ideation-service
spec:
  type: NodePort
  selector:
    app: ideation
  ports:
    - port: 8080
      targetPort: 8080