apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-config
data:
  profile: develop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ideation
  labels:
    app: ideation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ideation
  template:
    metadata:
      labels:
        app: ideation
    spec:
      containers:
        - name: ideation
          image: org.ideation/rest-layer:0.0.1-SNAPSHOT
          env:
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  name: profile-config
                  key: profile
              #value: develop
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ideation-service
spec:
  selector:
    app: ideation
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ideation
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ideation.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ideation-service
                port:
                  number: 8080