#Shared properties with all the profiles
server:
  port: 8080

spring:
  profiles:
    active: ${PROFILE}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
