version: '3.8'
services:
  resource-service:
    container_name: resource-service
    image: org.ideation/rest-layer:2024.1.3
    environment:
      - PROFILE=develop
    ports:
      - 8081:8080
    networks:
      - web-facing

networks:
  web-facing:
    name: web-facing
    driver: bridge